### ISSUE TITLE
Ensure all relevant JS files are included after alphagov/govuk_elements#183 is merged

### ISSUE THREAD

**Issue by robmckinnon** [alphagov/govuk_elements_rails#10]
A pending PR on the `govuk_elements` repo is going to add new javascript files, see here: https://github.com/alphagov/govuk_elements/pull/183

We need to ensure these new javascript files are added to the gem.

Currently to add a javascript file to the gem, we create a new symlink to the file from `govuk_elements`, like in this example:
```
cd vendor/assets/javascripts/
ls -l
ln -s ../../../govuk_elements/public/javascripts/vendor/details.polyfill.js .
ls -l
cd ../../..
git add vendor/javascripts/details.polyfill.js
```

Using this approach we'd need to add each new javascript file separately. We could revisit this, and maybe symlink to javascript subdirectories from `govuk_elements`.

**Comment by robinwhittleton** [comment]
JS ended up being included in govuk_frontend_toolkit.
